// Edit this file to update the repeatable content on the homepage.
window.SITE_CONTENT = {
  mapAreas: [
    { name: "工作城", icon: "▣", x: 18, y: 30, target: "work" },
    { name: "成长营地", icon: "↑", x: 42, y: 20, target: "growth" },
    { name: "生活村", icon: "⌂", x: 80, y: 30, target: "life" },
    { name: "思考塔", icon: "?", x: 79, y: 70, target: "reflection" },
    { name: "像素信箱", icon: "@", x: 25, y: 70, target: "contact" },
  ],
  growthItems: [
    { code: "QUEST 01", icon: "+", title: "持续学习", description: "对新问题保有耐心和好奇，把每天的输入变成真实经验。" },
    { code: "QUEST 02", icon: "RL", title: "深入强化学习", description: "继续理解强化学习，也让研究方向和工作中的问题彼此连接。" },
  ],
  sideQuests: [
    { icon: "☁", title: "看云", subtitle: "CLOUD WATCHING", description: "没有目标，也没有打卡。只是偶尔抬头，看看今天的天空刷出了什么。", color: "sky" },
    { icon: "♫", title: "听歌与唱歌", subtitle: "MUSIC & SINGING", description: "歌单很长，曲风很杂。喜欢听，也喜欢自己唱几句。", color: "peach" },
    { icon: "▣", title: "小说与小短剧", subtitle: "STORIES", description: "不一定深刻，但足够上头。休息有时候就是允许大脑暂时离线。", color: "cream" },
  ],
  games: ["英雄联盟", "无畏契约", "APEX", "胡闹厨房", "土豆兄弟", "杀戮尖塔", "求生之路", "…"],
  recentTracks: [
    { title: "What You Won't Do for Love", artist: "Bobby Caldwell", url: "https://y.qq.com/n/ryqq/songDetail/004ZzRxD0ZSTXu" },
    { title: "明明 (深爱着你)", artist: "丁肆Dicey", url: "https://y.qq.com/n/ryqq/songDetail/001quxhi3e5a9V" },
    { title: "All The Time", artist: "Bahamas", url: "https://y.qq.com/n/ryqq/songDetail/000k2wnT1wIw4M" },
  ],
  bgmTracks: [
    {
      title: "下班后的云",
      subtitle: "舒缓模式",
      tempo: 360,
      lead: "sine",
      duration: 0.58,
      melody: [69, null, 73, null, 76, 73, null, 71, null, 68, null, 71, 74, null, 71, null],
      bass: [45, 42, 38, 40],
      bassEvery: 4,
      bassType: "triangle",
      accentEvery: 8,
    },
    {
      title: "散步练习",
      subtitle: "轻松模式",
      tempo: 235,
      lead: "triangle",
      duration: 0.18,
      melody: [64, 71, 67, 74, 66, 73, 69, 76, 64, 71, 67, 74, 62, 69, 66, 73],
      bass: [40, 47, 42, 45, 40, 47, 38, 45],
      bassEvery: 2,
      bassType: "sine",
      accentEvery: 4,
    },
    {
      title: "周末联机厅",
      subtitle: "欢快模式",
      tempo: 125,
      lead: "sawtooth",
      duration: 0.09,
      melody: [72, 72, 79, 76, 74, 74, 81, 79, 72, 76, 79, 84, 83, 79, 76, 74],
      bass: [36, 36, 43, 43, 41, 41, 38, 43],
      bassEvery: 2,
      bassType: "square",
      accentEvery: 2,
    },
  ],
  reflections: [
    { code: "SIGNAL 01", title: "更好地使用 AI", description: "不只感慨它的强大，也认真学习怎么用，并帮助身边的人一起用。" },
    { code: "SIGNAL 02", title: "守住生活的边界", description: "学会平衡工作与生活，不让自己只剩下被消耗的状态。" },
    { code: "SIGNAL 03", title: "接住成年人的责任", description: "身份在变化，也开始理解那些随之而来的关系、选择与责任。" },
  ],
};
